version: "3.2"
services:
  app:
    image: matrixdotorg/synapse
    restart: always
    volumes:
      - synapse-data:/data
    networks:
      - backend

  proxy:
    image: nginx:1.21.4-alpine
    restart: always
    depends_on:
      - app
    volumes:
      - ./synapse-proxy.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - host.env
    networks:
      - certs
      - backend

volumes:
  synapse-data:
    name: synapse-data
    external: true

networks:
  certs:
    name: certs
    external: true
  backend:
