version: "3.2"
services:
  database:
    build: database
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    secrets:
      - psql_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_password
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    networks:
      - backend

  app:
    image: matrixdotorg/synapse
    restart: always
    depends_on:
      - database
    volumes:
      - synapse-data:/data
    networks:
      - backend

  proxy:
    image: nginx:1.21.4-alpine
    restart: always
    depends_on:
      - app
    volumes:
      - ./synapse-proxy.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - host.env
    networks:
      - certs
      - backend

volumes:
  synapse-data:
    name: synapse-data
    external: true
  database:

networks:
  certs:
    name: certs
    external: true
  backend:

secrets:
  psql_password:
    file: ./psql_password.txt
